on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit package.json and package-lock.json
        run: |
          git config user.email "1310.runnymede.robotics@gmail.com"
          git config user.name "Runnymede Robotics CI"
          git add package.json package-lock.json
          git commit -m "chore(release): update package.json and package-lock.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Deploy
        run: |
          git config user.email "1310.runnymede.robotics@gmail.com"
          git config user.name "Runnymede Robotics CI"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}